### ISSUE TITLE
Typo in UserInput.Mouse

### ISSUE THREAD

**Issue by Rocky28447** [Sleitnick/AeroGameFramework#10]
In UserInput.Mouse the following methods incorrectly list their returned value as Vector3s rather than Vector2s:

-Mouse:GetPosition()
-Mouse:GetDelta()

![image](https://user-images.githubusercontent.com/26193486/42406215-eabea4d0-8170-11e8-9ee0-3a8f74137951.png)

**Comment by Sleitnick** [comment]
Thanks, this has been corrected
