### ISSUE TITLE
FireAllClientsEventExcept(String clientEventName, Player client, ...)

### ISSUE THREAD

**Issue by Masken8** [Sleitnick/AeroGameFramework#103]

**Comment by Sleitnick** [comment]
This is fantastic timing. I was just thinking of adding this yesterday.

**Comment by Masken8** [comment]
Noice 👍

**Comment by Sleitnick** [comment]
My implementation so far will look something like this:

```lua
function AeroServer:FireAllClientsEventExcept(eventName, client, ...)
	local event = self._clientEvents[eventName]
	for _,player in pairs(players) do
		if (player ~= client) then
			event:FireClient(player, ...)
		end
	end
end
```

And the `players` list will be dynamically kept up-to-date.

**Comment by Sleitnick** [comment]
Added. See: https://github.com/Sleitnick/AeroGameFramework/commit/96160092b46ed1306af8b8be6182e9a43d4a57ce#diff-7976a7680467adfe553e9a0dca71a52f
