### ISSUE TITLE
RegisterClientEvent Not Working [solved]

### ISSUE THREAD

**Issue by LukeGabrieI** [Sleitnick/AeroGameFramework#108]
This could be temporary, but every time I try making a RemoteEvent using RegisterClientEvent, it does not work. Please fix, thanks.

**Comment by Sleitnick** [comment]
Can you provide some examples to reproduce this issue?

**Comment by LukeGabrieI** [comment]
Server-Script: https://pastebin.com/5swRZiqj

So, basically what I'm trying to do is create a RemoteEvent which will then be fired to the client. I put the function as a shared function just so that the later module script function thingy (BallModule:AttemptParent()) would make the event work. Regardless, this is where the [Module]([![Screenshot from Gyazo](https://gyazo.com/e397c529f3b41284f80939d1701af561/raw)](https://gyazo.com/e397c529f3b41284f80939d1701af561)) is located, and this is how I require the [Module]([![Screenshot from Gyazo](https://gyazo.com/da291f457804b8a923bacfe7a3a381c1/raw)](https://gyazo.com/da291f457804b8a923bacfe7a3a381c1)).

**Comment by Sleitnick** [comment]
Your tool shouldn't be explicitly requiring any modules for the framework. If you're accessing framework modules from the server, use `_G.AeroServer` instead. For instance, to reference the Ball Service:

```lua
while not _G.AeroServer do wait() end -- Wait for framework initialization if needed
local BallService = _G.AeroServer.Services.BallModule
```

However, the actual issue you're having is in regards to the top section of your Ball Service module. You reference `local Tool = script.Parent.Parent.Parent`, which in this context would just equal the `ServerStorage` object, not a tool. However, then you try to wait for objects like `local ToolValues = Tool:WaitForChild("Values")`, but that probably doesn't exist in `ServerStorage`, thus it waits forever.

**Comment by LukeGabrieI** [comment]
Okay, thank you so much for your help. I'm transitioning into using modules for my game now and I'm really glad that you made tutorials for your own framework. Keep up the good work!

**Comment by LukeGabrieI** [comment]
I actually had the ball module in the tool at the beginning, but now that I can access it from server storage, I'm going to redo the coding for it. [![Screenshot from Gyazo](https://gyazo.com/2bb28fb0fd4fe524c5286b424d32bc9d/raw)](https://gyazo.com/2bb28fb0fd4fe524c5286b424d32bc9d)

**Comment by Sleitnick** [comment]
Cool, glad you got it to work!
