### ISSUE TITLE
UserInput:Get("Mouse") not working

### ISSUE THREAD

**Issue by Syslog777** [Sleitnick/AeroGameFramework#112]
https://gyazo.com/f8887ef6e0c804044c6b782f90d3bacd
Mouse is a field in the controller script.
https://gyazo.com/ecc9e24cf34098d44a16379fa3108fe2
I use UserInput:Get(module name) but it does not load the module. I see you have used WrapModule. How can I fix this?

**Comment by Syslog777** [comment]
Nvm, I was using it from Init, which isnt safe.

**Comment by Sleitnick** [comment]
Yup, you got it. The `UserInput` module's `Init` method loads all the controller modules under it.

However, if you want to use it from your other `Init`s, then you could set the UserInput's __aeroOrder to something like 1:

```lua
local UserInput = {}
UserInput.__aeroOrder = 1 -- Add this line
```

As long as your module either doesn't have `__aeroOrder` defined or has it defined as a larger number then it would initialize after the Input module.
