### ISSUE TITLE
Infinite yield possible on ReplicatedStorage.Aero:WaitForChild("AeroRemoteServices")

### ISSUE THREAD

**Issue by insertLenny** [Sleitnick/AeroGameFramework#113]
I got AeroGameFramework, ran the installer and I'm using Rojo with VSCode

However, none of my services will load and the AeroClient script (StarterPlayerScripts/Aero/Internal/AeroClient) just warns "Infinite yield possible" for "AeroRemoteServices"

**Comment by Sleitnick** [comment]
Have you written any code yourself yet, or is it a clean install? If you have written any code, I would look at the code you have either in the `Init` function or outside of any functions in the module (i.e. code at the top of the file or whatever). Make sure nothing is yielding there.

**Comment by insertLenny** [comment]
Thanks a lot! Turns out all I had was a typo in the Init 🤦‍♀️
