### ISSUE TITLE
Be more specific when you cannot register function/event after Init method

### ISSUE THREAD

**Issue by insertLenny** [Sleitnick/AeroGameFramework#114]
If Aero errors `Cannot register function after Init method` or `Cannot register event after Init method`, it would be great if it would be more specific (e.g. in what service/controller and the function's name)

**Comment by Sleitnick** [comment]
Does the stack trace not indicate which module the error is coming from?

**Comment by Sleitnick** [comment]
Closing due to lack of clarification
