### ISSUE TITLE
VS Code Live Share

### ISSUE THREAD

**Issue by LukeGabrieI** [Sleitnick/AeroGameFramework#115]
Is there a way to share my code through Live Share on VS Code? I would like to share my code with another friend of mine so that scripting will be easier.

**Comment by Sleitnick** [comment]
I'm not sure. I've never used VS Code Live Share. Is this something that the extension would have to add, or is it something that Live Share will handle? I'm not sure if this is in scope for this project.

**Comment by Sleitnick** [comment]
Closing for now due to inactivity

**Comment by spectrius** [comment]
At the moment I think this does not work as **/src** is no longer in the root directory when you enable Live Share, the structure is **liveshare/root/src** (inaccurate names, but you get the gist)

If you try to open AGF explorer while in Live Share, you get this error:
![image](https://user-images.githubusercontent.com/18365144/82014603-428f7e00-967d-11ea-8a65-67ff3b3c7725.png)
