### ISSUE TITLE
Cannot put Controllers in descendant folder of the Controllers folder

### ISSUE THREAD

**Issue by Masken8** [Sleitnick/AeroGameFramework#117]
I want to have a Folder inside the Controllers Folder with Controllers in it for organization purposes but that doesn't seem to be possible currently

**Comment by Reshiram110** [comment]
It should be? This issue was addressed in https://github.com/Sleitnick/AeroGameFramework/issues/85.

**Comment by Masken8** [comment]
Well when I click the plus button for the folder the Gui is saying I'm creating a module and not a controller

**Comment by Sleitnick** [comment]
The in-Studio plugin is no longer supported & thus won't be updated to support nested folders. The VS Code extension is the preferred method for developing with AGF.

Follow the guide on the [documentation site](https://sleitnick.github.io/AeroGameFramework/) for more information on setting up AGF with VS Code.
