### ISSUE TITLE
Creating a new project with VS Code extension creates DataService along with it's dependencies

### ISSUE THREAD

**Issue by Dog2puppy** [Sleitnick/AeroGameFramework#121]
When creating a new project using the extension, the DataService and DataStoreCache are all created. These all have the contents of `404: Not Found`

**Comment by Sleitnick** [comment]
Thanks for the report! It looks like the `filelist` wasn't updated correctly. I'll fix that right away.

**Comment by Sleitnick** [comment]
Should now be fixed since https://github.com/Sleitnick/AeroGameFramework/commit/e9c7254b2eb3d8ff6cd98560e0d0eac54678dc31

**Comment by Sleitnick** [comment]
Should now be fixed from https://github.com/Sleitnick/AeroGameFramework/commit/e9c7254b2eb3d8ff6cd98560e0d0eac54678dc31
