### ISSUE TITLE
Data module needs to handle player re-entries

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/AeroGameFramework#125]
When a player leaves, the Data module delays for a bit, saves the data, and destroys the data instance for that player.

However, what happens if a player re-enters the server between the delay period when the player left and the data is saved? In such an instance, the save cycle should be cancelled.

But another problem arises: What if the player had gone to yet another server in-between these two times?

**Comment by Reshiram110** [comment]
I solved this problem with a two-part queue.

I have a two tables named `LoadQueue` and `SaveQueue`. When a player joins, the following code is ran (pseudocode):
```lua
Players.PlayerAdded:connect(function(Player)
    if not IsPlayerInLoadQueue(Player) then --A load operation is not being done for the player already
        if IsPlayerInSaveQueue(Player) then --Player's data is being saved, wait for operation to finish
            while true do
                if not IsPlayerInSaveQueue(Player) then
                    break
                    RunService.Stepped:wait()
                end
            end
        end
        -- Load player's data here
    end
end)
```

Saving data is the same, except you reverse the queue checks (make sure player's data isn't currently being saved, then wait for load to finish). In addition to this, you can store two values in the datastore, `IsSaving` and `IsLoading`. This would allow you to share the 'queue' across multiple servers.

**Comment by brinkokevin** [comment]
What I ended up doing in my DataService is saving some info about the save to the players data table.

```
playerDataTable.Save = {
       Type = "AutoSave" or "PlayerLeft"; --What kind of save
       Time = os.time(); --When was it saved
}
```
then based on this data every time the player joins a server I retry up to 5 times attempting to wait for player data which was saved as "PlayerLeft" with 6 sec delays between each retry. I have been tracking how many retries it takes to get data which was saved as "PlayerLeft". Most of the time for players who left the game and joined later there are no retries required. When players quickly join a different server I can see most of the time there is only 1 retry but in some cases, there appear to be up to 3 retries. 

I am not using save time yet but I plan to add that to prevent players from having to wait through all 5 retries if their PlayerLeft data failed to save the last time they played. I will check if the last save time was over an hour ago and just go with the data that was saved as AutoSave.

**Comment by brinkokevin** [comment]
Also, the Data module shouldn't delay, but instead, have a way to connect our own functions that should be called before data gets saved and catch removed.

**Comment by Sleitnick** [comment]
Data module will be deprecated in favor of ProfileService. See: https://github.com/Sleitnick/AeroGameFramework/issues/194
