### ISSUE TITLE
Crashes ROBLOX Studio.

### ISSUE THREAD

**Issue by DrShockz** [Sleitnick/AeroGameFramework#129]
This seems to crash Roblox studio, and it also stops me from loading into some of my projects with this installed without crashing! Very odd.

**Comment by n00kii** [comment]
make sure you don't have any dangerous beta features active

**Comment by DrShockz** [comment]
Ahh! Thanks, I have like every beta feature on.

**Comment by Sleitnick** [comment]
According to Roblox [release notes for 422](https://developer.roblox.com/en-us/resources/release-note/Release-Notes-for-422), this should be fixed now.
