### ISSUE TITLE
[Feature] Universe Syncing System

### ISSUE THREAD

**Issue by Dog2puppy** [Sleitnick/AeroGameFramework#13]
A universal syncing system in the plugin for multi-place games would be very useful. 

My idea
Place 1: Make changes -> Press upload -> Plugin uploads to GitHub or GitLab

Place 2: Open place -> Press sync -> Downloads latest version of framework (with all custom services and stuff) from GitHub/GitLab

**Comment by Sleitnick** [comment]
Interesting. I definitely have needed to sync code up between places in the same game universe, which involved a lot of copy-and-pasting, and that easily gets out of sync.

The best way to do this would be through LinkedSource scripts, but that doesn't necessarily help with keeping the actual script objects (e.g. creating/deleting/moving) in sync.

There's also the issue if you're developing locally (i.e. not opening the place from the cloud), in which it is not linked to a 'Game', and thus cannot utilize LinkedSources, nor is it aware of other places within the same game universe.

I will keep brainstorming some ideas, but it's possible that this might be out of scope for this framework for now.

**Comment by kevinsarlah** [comment]
The project I am currently working on has 9 places that have to be synced when anything is changed. My solution to that was to make a script which packs everything from certain directories & publishes it as a model which is then synced in real time when a new server opens.

Here is the code maybe something similar could be added to Aero https://pastebin.com/qP7WtQVp

**Comment by Sleitnick** [comment]
For now I am going to close this because I think it's a bit out of scope for this framework at the moment. Maybe this will be more feasible later down the line when the framework becomes more mature.

**Comment by Dog2puppy** [comment]
Has there been an updated way to do this, @Sleitnick ?
