### ISSUE TITLE
Add swiping to the mobile input

### ISSUE THREAD

**Issue by Dog2puppy** [Sleitnick/AeroGameFramework#135]
Roblox provides UserInputService.TouchSwipe that fires for swipes up, down, left, and right. In my experience, this doesn't work very well due to the lack of diagonal swipes. This event is also completely missing from AeroGameFramework. Adding an improved version to the framework with support for diagonal swipes would make it easier to create custom character controllers.

**Comment by Sleitnick** [comment]
Many new mobile methods/events were added in https://github.com/Sleitnick/AeroGameFramework/commit/622c888ec2175b00c8d72c379609431473d58fb2, including `TouchSwipe`. However, I will leave it up to developers to provide their own logic for diagonal swipes.

The `TouchSwipe` event is used to mimic swipe events in most popular mobile interfaces, which typically only include horizontal and vertical swipe detection.

**Comment by Dog2puppy** [comment]
I think I'm blind because I didn't see TouchSwipe a few days ago. I'll try to implement diagonal swipes myself then. Thanks!

**Comment by Dog2puppy** [comment]
oh wait you added them a few minutes ago. That's why I didn't see them a few days ago.
