### ISSUE TITLE
StoreService Doesn't allow returning NotProcessedYet

### ISSUE THREAD

**Issue by Dog2puppy** [Sleitnick/AeroGameFramework#144]
On the Roblox Developer Hub, it says
> Do not return PurchaseGranted if the product could not be granted.

AeroGameFramework does not allow this with the current implementation. There are many use cases for not returning PurchaseGranted. One use case is for starter packs with a timer on them. You need to be able to return NotProcessedYet if the starter pack was already purchased or if the starter pack expires. Another use case if for round based games where players can purchase boosts before the round begins. You need to be able to return NotProcessedYet if the round starts before the player purchases it. 

I think something like `StoreService:RegisterProductCallback(productId: number, callbackFunction: (player, receiptInfo) => Enum.ProductPurchaseDecision)` would solve this. The current `StoreService.PromptPurchaseFinished` event would still fire even if a product callback is registered for the product to allow for analytics, such as sending the data to GameAnalytics or Google Analytics.

**Comment by Dog2puppy** [comment]
Should I start a pull request to start adding this?

**Comment by Sleitnick** [comment]
TBH I'm thinking about removing the StoreService. It forces devs into a very precise model that might not work for everyone.

**Comment by Sleitnick** [comment]
StoreService will be removed

**Comment by Dog2puppy** [comment]
rip StoreService ????-2020
