### ISSUE TITLE
[Feature Request] New Event Type

### ISSUE THREAD

**Issue by Masken8** [Sleitnick/AeroGameFramework#147]
An Event type that can be listened to on both Client and Server but only fired from the Server would be really handy, currently you can't do that without extra code

**Comment by Sleitnick** [comment]
Can you provide a code sample of how you currently do this?

**Comment by Masken8** [comment]
```lua
local MyService = {}

local MY_EVENT = "MyEvent"

function MyService:Start()
    self:ConnectEvent(MY_EVENT, function(myVar)
        self:FireAllClientsEvent(MY_EVENT, myVar)
    end)
end

function MyService:Init()
    self:RegisterEvent(MY_EVENT)
    self:RegisterClientEvent(MY_EVENT)
end

return MyService
```

**Comment by Sleitnick** [comment]
I've thought about doing this in the past, but have decided to not implement it because there are too many edge cases to be covered to make it worth it. I think for now it's easier for developers to add their own wrappers to do this for them. E.g.:

```lua
function MyService:FireBoth(eventName, ...)
	self:FireAllClients(eventName, ...)
	self:Fire(eventName, ...)
end
```
