### ISSUE TITLE
[Bug] Double clicking scripts no longer opens them

### ISSUE THREAD

**Issue by Rocky28447** [Sleitnick/AeroGameFramework#15]
Scripts can no longer be opened through the Aero plugin.

**Comment by Rocky28447** [comment]
Seems to be an issue with OpenScript(), as your Create Script plugin doesn't seem to open scripts either.

**Comment by Sleitnick** [comment]
I can confirm that the `plugin:OpenScript()` method is not working. It doesn't even throw an error. I have reported this as a Studio Bug and will keep this issue updated regarding any word or fix with the problem.

**Comment by Sleitnick** [comment]
A simple repro for this:

1. Create any script in Studio
2. Select the script
3. Run the following code:
```lua
print("Opening...")
PluginManager():CreatePlugin():OpenScript(game.Selection:Get()[1])
print("Opened?")
```

**Comment by Rocky28447** [comment]
Gave the thread a like on the Devforum. 😄

**Comment by Rocky28447** [comment]
I don't see anything wrong there :thinking:

**Comment by Dog2puppy** [comment]
In the first image there’s somehow about 15 viewports, and in the second image AGF main widget is black, AGF code widget is fine, and Doc Reader is all glitches and has some of AGF at the bottom.

**Comment by Sleitnick** [comment]
@Rocky28447 Yes I'm frustrated about it too. It heavily interrupts my whole development workflow. I will continue bumping the DevForum thread until it gets fixed.

**Comment by Sleitnick** [comment]
Finally got an official word: "This should be fixed in the next release."

So, this should hopefully be fixed by the weekend. Will continue to keep this updated.

**Comment by Rocky28447** [comment]
Awesome! Fingers crossed. :crossed_fingers:

**Comment by Dog2puppy** [comment]
Now if only they fixed the graphical glitches that seem to get worse and worse for me.

**Comment by Sleitnick** [comment]
This was finally fixed in tonight's Studio release

**Comment by Dog2puppy** [comment]
Atleast the plugin is halfway useable now.

**Comment by Rocky28447** [comment]
Yep, can confirm!

**Comment by Sleitnick** [comment]
@Dog2puppy Please open up an issue for any bugs or issues that you encounter with the plugin. I want to work to make it much more usable.

**Comment by Dog2puppy** [comment]
It’s a Roblox issue unfortunately. I’ve reinstalled but it still goes crazy.
