### ISSUE TITLE
Access controller/service from standalone scripts

### ISSUE THREAD

**Issue by insertLenny** [Sleitnick/AeroGameFramework#150]
Is there a way to access a controler/service's functions from a Script/LocalScript that isn't related at all to AGF?
More details:
>I'm trying to make a command with [Cmdr](https://eryn.io/Cmdr) (a neat command line in-game), but the problem is that you can only make commands using separate ModuleScripts, where you specify a function for each command, like this:
> ```lua
> ClientRun = function(_, argument)
> 	local myController = ?
>
> 	return myController:DoSomethingWith(argument)
> end
> ```

**Comment by Sleitnick** [comment]
Yup, this is possible by using `_G.Aero`! In your case, it could be like this:

```lua
while (not _G.Aero) do wait() end
ClientRun = function(_, argument)
	local myController = _G.Aero.Controllers.MyController
	return myController:DoSomethingWith(argument)
end
```

See the documentation on external use: https://sleitnick.github.io/AeroGameFramework/execution_model/#external-use
