### ISSUE TITLE
UserInput Prevents Disabling MouseIcon

### ISSUE THREAD

**Issue by sebastianrasor** [Sleitnick/AeroGameFramework#151]
The UserInput controller prevents enabling/disabling the mouse icon, even when using the `:SetMouseIconEnabled` method provided by `UserInput:Get("Mouse")`. This is caused by lines 59-69 of the UserInput controller.

**Comment by sebastianrasor** [comment]
```lua
local function ChangePreferred(newPreferred)
    if (self._preferred ~= newPreferred) then
        self._preferred = newPreferred
        self.PreferredChanged:Fire(newPreferred)
        if (newPreferred == self.Preferred.Mouse or newPreferred == self.Preferred.Keyboard) then
            userInput.MouseIconEnabled = true -- issue
        else
            userInput.MouseIconEnabled = false -- also an issue
        end
    end
end
```

**Comment by Sleitnick** [comment]
Thanks for the report! This is definitely a problem. The lines you highlighted are recent additions, but they step on the toes of the Mouse module.

I will probably fix this by making mouse hiding an optional feature that is off by default.

**Comment by Sleitnick** [comment]
Pull request merged https://github.com/Sleitnick/AeroGameFramework/pull/152
