### ISSUE TITLE
Can't set false as a default value

### ISSUE THREAD

**Issue by MatheoLESNE** [Sleitnick/AeroGameFramework#159]
Hello,

I tried getting a new variable (which didn't existed before) and setting the default value to false with :
`
local success, value = DataFile:Get("MuteOption", false):Await()
`
but i get an error saying the first argument must be a table.

**Comment by Sleitnick** [comment]
Looks like you found a bug! This is because the `defaultVal` is checked as a "truthy" value on line 489 of the Data module.

The current line looks like this:
```lua
value = (typeof(defaultVal) ~= "table" and defaultVal or tableUtil.Copy(defaultVal))
```

However, it _should_ be changed to the following:
```lua
value = (typeof(defaultVal) ~= "table" and defaultVal ~= nil or tableUtil.Copy(defaultVal))
```

Note the addition of `~= nil` after the `and defaultVal`.

**Comment by Sleitnick** [comment]
The solution is to replace this with an `if` statement:

```lua
if (typeof(defaultVal) == "table") then
   value = tableUtil.copy(defaultVal)
else
   value = defaultVal
end
```

I'll add in this change soon.

**Comment by Sleitnick** [comment]
Fixed in https://github.com/Sleitnick/AeroGameFramework/pull/163
