### ISSUE TITLE
Scripts with __call metamethod will error

### ISSUE THREAD

**Issue by OverHash** [Sleitnick/AeroGameFramework#168]
Any shared/module script with a `__call` metamethod will error during its usage. This is problematic for modules such as DataStore2.

The reasoning behind this is because the LazyLoadSetup function, https://github.com/Sleitnick/AeroGameFramework/blob/f8cd24f4104508f0a1b6e3e6d48b777e56e2bc3d/src/ServerScriptService/Aero/Internal/AeroServer.server.lua#L146-L165 does a check on all modules it requires to see if it is a table, and then uses `Aero:WrapModule` which uses the module like a table.

This obviously errors for things with a `__call` metamethod since they are a "function", not a table.

**Comment by OverHash** [comment]
This can be easily fixed by using __call after requiring the module!
```lua
local test1 = {}
local test2 = {__call = function()
	
end}

local test3 = setmetatable({}, {__call = function() end})

local isTable = function(x)
	local mt = getmetatable(x)
	if mt and mt.__call then
		return false
	end
	
	return true
end

print(isTable(test1)) --> true
print(isTable(test2)) --> true
print(isTable(test3)) --> false
```

**Comment by colehans** [comment]
Ran into this issue while using the AGF and DataStore2 as well. I ended up just adding a flag called __aeroPreventWrapping that gets checked by LazyLoadSetup function, you give up the functionality of an aero service but the original metatable is preserved.

**Comment by Sleitnick** [comment]
Should be good to go now. Thanks for reporting this issue.
