### ISSUE TITLE
Require module from another module?

### ISSUE THREAD

**Issue by insertLenny** [Sleitnick/AeroGameFramework#178]
I'm making a module AnimHandler, but I need access to the AnimationIds module. Both are inside client>modules. Are there any injected properties I can use to access AnimationIds, or do I need to use _G.Aero?

**Comment by spectrius** [comment]
If both are placed directly in Client.Modules, you should be able to access AnimationIds by referencing `self.Modules.AnimationIds` or vice versa.

**Comment by insertLenny** [comment]
The problem is, referencing `self` doesn't give out the properties, instead, because I'm accessing it in a class module, it returns the object

**Comment by spectrius** [comment]
You can still get a reference to it by using `self` where it refers to the module itself. For example, you could put the reference in `:Init()`, which should work with all Aero-wrapped modules.

```
local AnimationIds

function AnimHandler.new()

end

function AnimHandler:Init()
    AnimationIds = self.Modules.AnimationIds
end
```

**Comment by insertLenny** [comment]
Thanks! Managed to get it working 😃
