### ISSUE TITLE
Run Init async and use promises to await completion

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/AeroGameFramework#181]
Currently, `Init` methods are executed synchronously to guarantee they're all completed before `Start` methods are executed.

To improve startup speed, it might be better to run all `Init` methods asynchronously and then await them as promises before moving onto the `Start` methods.

Because all `Init` methods are intrinsically self-isolated (by practice, they should never be talking to other modules in the framework except for declaring references), there should be no side-effects of such a change, except for the negation of the existing `__aeroOrder` flag to control initialization order. It's possible that `__aeroOrder` could still be respected by guaranteeing the order if explicitly set. In other words, modules with `__aeroOrder` set would still act in synchronous fashion, whereas modules without the flag set would all execute at the same time together.

Example:

```lua
local inits = {}
for _,service in ipairs(serviceTables) do
	table.insert(inits, Promise.Async(function(resolve, reject)
		InitService(service)
		resolve()
	end))
end
Promise.All(inits):Await()
```

**Comment by OverHash** [comment]
Perhaps Aero should run `__aeroOrder` ones first, *then* run all the rest asynchronously. This would get the bost of both worlds, particularly the users that never use `__aeroOrder`

**Comment by Sleitnick** [comment]
I'm going to close this for now. The minor performance gain is not really worth implementing this at this time.
