### ISSUE TITLE
VSCode seeing nested module's parent as a folder

### ISSUE THREAD

**Issue by insertLenny** [Sleitnick/AeroGameFramework#182]
When you nest another module inside a module (with the AGF Explorer in the left), you can't open the parent module! This means you need to move all descendants into another place before being able to  read the code inside the main module (in this case `DataStore2`). When you close the editor for that file, it's basically lost, unless you resort to editing from Studio. GIF: https://gyazo.com/a3e43dd91b627f8c320670af264d90f3

**Comment by Sleitnick** [comment]
Have you tried clicking on another module and then clicking it again? Sometimes it won't reopen a script you already have selected (which admittedly is another bug that needs to be addressed).

**Comment by insertLenny** [comment]
Yes, this works when clicking another module before opening your original intended one.

**Comment by Sleitnick** [comment]
Cool! There's an updated issue here that will follow this bug, so I'll close this one to avoid duplicates

https://github.com/Sleitnick/AeroGameFramework/issues/185
