### ISSUE TITLE
Deprecate TableUtil.Print()

### ISSUE THREAD

**Issue by Rocky28447** [Sleitnick/AeroGameFramework#183]
With the [overhaul and complete revamp of Roblox Studio's output window](https://devforum.roblox.com/t/expressive-output-window-beta/642684), passing a table to the global print() function will print an expandable version of the table to the output with all contents visible. Accordingly, TableUtil.Print() no longer has any real reason to exist.

**Comment by OverHash** [comment]
please dont, i dont like the new output, and you cant do things like label tables as easy.

**Comment by Sleitnick** [comment]
I'll evaluate this once it is out of beta

**Comment by Sleitnick** [comment]
For the time being, I'm going to close this. We can revisit later. The current feature in Studio is terrible. If they improve it, let's reopen this.

**Comment by OverHash** [comment]
Additionally, it doesn't work in games, so that's a big downside to deprecating this custom table print

**Comment by Rocky28447** [comment]
I agree, I opened this issue too hastily before I knew how terrible the new output's performance was.
