### ISSUE TITLE
Add ProfileService

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/AeroGameFramework#192]
Add loleris' [ProfileService](https://github.com/MadStudioRoblox/ProfileService) as a server-side module. ProfileService is a great data tool and addresses many common problems.

**Comment by howmanysmall** [comment]
Would it be reformatted? The actual module itself is formatted really poorly and it makes it hard to read.

**Comment by Sleitnick** [comment]
@howmanysmall The exposed [API](https://madstudioroblox.github.io/ProfileService/api/) matches the AGF coding style though. So I don't think I'd make any changes myself.
