### ISSUE TITLE
Implementation modules vs. framework provided modules collisions

### ISSUE THREAD

**Issue by jeremy-wilson** [Sleitnick/AeroGameFramework#23]
I am concerned about users of the framework adding their own modules and services and then the framework maturing and adding additional framework modules where the names conflict with what has been implemented in a game project.

For example, we just added Base64 as a shared module. But what if someone already has a Base64 one they created custom for themselves? Perhaps we should make an add-ons folder in the framework or something like that, where we can provide additional framework services, modules, controllers and shared modules which the user can include in their implementation if desired.

Additional thought needs to be made around this, but it will be a problem in the future as we look to expand on what the framework offers.

**Comment by jeremy-wilson** [comment]
Or, as a further thought, a separate repository of things they can install to their framework installation. Keep the base framework provided as only the framework, and extra "packages" of modules, controllers, services and shared available as installable packages.

**Comment by jeremy-wilson** [comment]
Aside from the collision concern, I would love to share my weather system, as an example. Would be great if I could create a package made up of a controller, a shared module and a server service which people could install into the Aero framework, and everything goes into its proper place. Having a framework supported way of doing this would be fantastic. I would imagine each addon having its modules, services, etc and then each add-on also having its own filelist.json, etc.

**Comment by Sleitnick** [comment]
This is good and should be carefully planned out before any attempt to implement. I won't have a lot of time to work on the framework this week, but will put this in my backlog.

**Comment by jeremy-wilson** [comment]
If we go the package management route, we would also need the ability for the package to declare dependencies. For example, I might have a contribution which depends on another shared module that is hosted as a separate add-on package. So dependency management in the package would have to be done as well.

But having a way to do something like this would allow for more people to contribute in an organized way and really expand the frameworks abilities through such add-ons.

**Comment by Sleitnick** [comment]
The new installer will inform the user of changes to existing files. Currently it is not smart enough to tell if the user made changes or if it's just an older version, thus it will prompt the user for each change (in a selectable list).

For now, this will be the solution for this issue. I would like to improve this system over the near future, but it's a bit out of scope at the moment.
