### ISSUE TITLE
Tag Dropdown on Installer/Updater

### ISSUE THREAD

**Issue by jeremy-wilson** [Sleitnick/AeroGameFramework#24]
When someone runs the installer/updater, it would be great if it could show a drop down of Github tags to install or update from. Each release SHOULD have a version tag in github, which would allow the installer to install or update from a particular version.

So, as an example, if someone installs the latest version and they have problems, they can simply run the installer/updater again and pick an earlier version. The list can simply be populated from the list of tags available in the github repo.

This is especially important as the framework advances and has BC breaks with previous versions.

However, some thought needs to be made around if someone updates to the latest, and then wants to rollback. If there were extra files/directories in the latest version, what do we do with those if someone wants to rollback to an earlier version? We don't want someone to loose any work, so maybe we inform them that they have to clean up extra files/folders? The installer can search for extra things and display a list to the user of things the updater did not touch, as consideration if the user needs to decide if they should clean those items up.

This is just a rough idea, but version support would be a great enhancement and big time saver for someone who adopted the framework and updates with unknown side effects due to BC breaks, etc.

**Comment by Sleitnick** [comment]
For the time being, I cannot do this because I would have to utilize the actual GitHub API, which has certain restrictions that I cannot currently support for this plugin. I do agree that this would be nice, but out of scope for now.

**Comment by jeremy-wilson** [comment]
Ok, thanks for the consideration. I will close the enhancement request.
