### ISSUE TITLE
ReplicatedFirst access to modules

### ISSUE THREAD

**Issue by kevinsarlah** [Sleitnick/AeroGameFramework#3]
There should be some way to setup ReplicatedFirst code and have access to client modules, remote events and remote functions.

**Comment by Sleitnick** [comment]
Instead of changing the framework structure, I have decided to include a template that developers can use, which is automatically added under ReplicatedFirst. It's a LocalScript named AeroLoad, and includes a robust example of how to use a custom loading GUI alongside the AeroGameFramework.
