### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Dog2puppy** [Sleitnick/AeroGameFramework#32]
I just noticed that this doesn't have a license at all. Please add one so I can't get sued for using this. 

Edit: GitHub has this tab here. Could be helpful for cleaning up this repo. 
https://github.com/Sleitnick/AeroGameFramework/community

**Comment by Sleitnick** [comment]
Agreed. I'll look into assigning the most proper one I can. I want to keep this fully open-sourced and allow people to freely use it and modify it at will.

**Comment by Sleitnick** [comment]
MIT
