### ISSUE TITLE
Studio hangs after closing Play Solo

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/AeroGameFramework#36]
Studio hangs for a very long time when you try to close out of Play Solo.

**Comment by Sleitnick** [comment]
This issue is not framework-related. It is caused by changes implemented in the new Accurate Play Solo feature. The issue happens when any YieldFunction is called within functions sent to the `game:BindToClose` method.

The fix has been made and will be rolled out with the next Studio release.

[More info](https://devforum.roblox.com/t/bindtoclose-100-infinite-yield/170469/27)

**Comment by Sleitnick** [comment]
Correction: This issue has not been fixed. It appears that the problem has been identified, but has not been resolved. This will remain open, but should be noted as a Roblox bug, and not a bug pertaining to this framework.

**Comment by kevinsarlah** [comment]
Temporary fix
```
if not game:GetService("RunService"):IsStudio() then
	game:BindToClose(GameClosing)
end
```

**Comment by Rocky28447** [comment]
I can confirm this is not a Roblox bug, rather a bug with the DataService's BindToClose method. This *was* a Roblox bug but it has since been fixed. The bug is now caused by the DataService's BindToClose connection.

**Comment by Rocky28447** [comment]
My mistake, this is actually NOT the fault of Aero.

**Comment by Rocky28447** [comment]
This is in fact a Roblox bug, my apologies for blaming Aero. However, I do believe they consider this bug to be fixed so I would recommend filing a bug report. I have sent this simple repro to CycloneUprising:

```lua
-- This function will yield for 5 seconds before resuming
function YieldExpect()
	
	local thread = coroutine.running()
	
	coroutine.wrap(function()
		wait()
		print("waiting 5 seconds")
		wait(5)
		print("resuming thread")
		coroutine.resume(thread)
	end)()
	
	print("yielding")
	coroutine.yield()
end

-- You would expect this to have the same result as YieldExpext, but this yields forever, or in our case 30 seconds because that is the shutdown deadline
game:BindToClose(function()
	
	print("game closing")
	local thread = coroutine.running()
	
	coroutine.wrap(function()
		wait()
		print("waiting 5 seconds")
		wait(5)
		print("resuming thread")
		coroutine.resume(thread)
	end)()
	
	coroutine.yield()
end)

-- Wait 1 second, call YieldExpect, then print "no longer yielding"
wait(1)
YieldExpect()
print("no longer yielding")
```

**Comment by Sleitnick** [comment]
This is _not_ an Aero bug. The framework is not using the method incorrectly. Using yields within `BindToClose` _should_ work just fine. Since using yields is not working (and is not directly tied to this framework), this is absolutely a Roblox-specific bug. I will be sure to report it.

I might consider adding a temporary work-around (e.g. just using 'waits' instead of coroutine yields), but I would prefer to have the actual issue addressed quickly.

Ideally, I'd like to keep the framework code the same if possible.

**Comment by Rocky28447** [comment]
I reported the bug as well in a DM to CycloneUprising (a DM where we had previous discussions about this bug) and received a response saying he would begin working on a fix promptly.

**Comment by Sleitnick** [comment]
@Rocky28447 Awesome. If you wouldn't mind, please update this issue if he gets back to you with any info or progress report on the problem, thanks!

**Comment by Dannyftm** [comment]
I simply added the studio check into the DataService Module for Aero and it removed the hang after closing Play Solo

**Comment by Rocky28447** [comment]
Yes, however that "fix" should not be necessary. This is a Roblox bug. I haven't heard any news lately on the fix for this bug so I will contact CycloneUprising when I can and ask for an update.

**Comment by PlanetDab** [comment]
Hey, new here. Can someone explain how I can achieve this workaround? The studio hanging while testing makes Aero almost unusable, due to the time spent waiting. I'm excited to get started with this framework, but off to a bad start. Thanks!

**Comment by Ductayp** [comment]
@Dannyftm can you tell me what line you put that check? I tried inserting the line inside the `DataService:BindToClose` function at line 248 of the DataService module and Studio still hangs after play solo. 

I really want to use this framework but this one issue would need to be resolved for it to be useful to me right now. Any help would be greatly appreciated.

**Comment by headjoe3** [comment]
Just commented out all of the asynchronous stuff, and I can confirm that coroutine.yield is definitely the issue.

Here's an idea - separate all saves into "closing chunks", which is some pool of BindToClose calls that deals with the next SetAsync call until the pool of remaining SetAsync calls is empty. 

And then, you can just call "BindToClose", say, 50 times, to generate 50 chunks that deals with SetAsync calls at close.

Whatever it is you do, this is a very critical bug for users of the framework and needs to be fixed. It's not Roblox's fault at this point.

**Comment by Sleitnick** [comment]
I asked if there was any update, and this is the response I got:

> "Sorry, no. Spent some time on it and could not figure out what exactly the problem was. Will try to prioritize a revisit." - CycloneUprising [[Source]](https://devforum.roblox.com/t/bindtoclose-100-infinite-yield/170469/56)

As for now, I will probably just patch it with a different technique, similar to what @headjoe3 has mentioned. It's unfortunate that this bug has persisted this long.

**Comment by Sleitnick** [comment]
I have pushed a temporary patch for this issue. It uses a BindableEvent and `spawn` to run bound functions on-close. It also uses `FlushAll` instead of `FlushAllConcurrent`. This should fix the issue for now. Once the issue is officially resolved regarding `coroutines`, I will re-enable the original code.

I am closing this issue. If anyone still experiences the problem, please let me know.
