### ISSUE TITLE
Use GetRequestBudgetForRequestType in SafeSataStore

### ISSUE THREAD

**Issue by Dog2puppy** [Sleitnick/AeroGameFramework#38]
https://www.robloxdev.com/api-reference/function/DataStoreService/GetRequestBudgetForRequestType

I’m not sure if this is a necessary requirement, but Roblox seems to recommend using this API for Data Stores. Probably would be fine without this, but it’s a good idea.

**Comment by Sleitnick** [comment]
Yes, the DataStore should be utilizing this feature to some degree. I might want to do an overhaul of the DataService anyway too. I would keep the API the same, but change the internals. There are nuances about the DataStoreService that I have learned today that have shifted my thinking around how data should be handled that was not previously documented.

**Comment by Dog2puppy** [comment]
Another part of the DataService redo is the auto save interval adjusting based on `GetRequestBudgetForRequestType`.

**Comment by Sleitnick** [comment]
FYI: This weekend, I am going to be creating a data loading/saving prototype. It will be completely independent from the existing data system. If all goes well, it might replace the existing system. I will make sure that the new system utilizes request budgets.

**Comment by Sleitnick** [comment]
Closing, because the new Data object will take precedent over any new features regarding DataStores within the framework. That being said, I will try to implement this within the new Data object as well.
