### ISSUE TITLE
Use GetService for game.Players

### ISSUE THREAD

**Issue by Dollar-500** [Sleitnick/AeroGameFramework#4]
If the name of game.Players is changed, then the framework will break because the scripts use game.Players instead of game:GetService("Players").

**Comment by Sleitnick** [comment]
Agreed. I have put this on my backlog. To take this a step farther, I want to make sure all services are retrieved using `GetService` instead of dot-notation due to the renaming possibility.

**Comment by Sleitnick** [comment]
This change has been made and committed. This change was made in the following modules:

- Fade controller [Client]
- PointsService [Server]
- StoreService [Server]
- DataService [Server]
- MockDataStoreService [Server]

In all cases, `game.Players` was replaced with `game:GetService("Players")`. Thank you again for your suggestion!

**Comment by Dollar-500** [comment]
Sounds good!
P.S. Someone suggested to me a few days ago to do this when using services. I just thought I'd post it since it was on my mind when I read this...
`local Services = setmetatable({}, {
	__index = function(self, Index)
		rawset(self, Index, game:GetService(Index))
		return rawget(self, Index)
	end
})`
