### ISSUE TITLE
Remove the PointsService

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/AeroGameFramework#44]
PointsService on Roblox's end is being deprecated soon. Therefore, there is no reason to have an Aero service for it. It should be removed.

**Comment by Dog2puppy** [comment]
When did Roblox announce the points service being deprecated? I know they removed leaderboards temporarily.

**Comment by Sleitnick** [comment]
@Dog2puppy Sorcus:

> Do not worry, the player points API will continue to function but we recommend using data stores if possible because they provide all of the functionality that player points do but are more likely to be supported long term.

Leaderboards on game pages are removed. There's a plan to create a new version at some point, with more flexibility. The current one wasn't built to scale well, which is why they removed it. There's no indication currently whether or not it will use the PointsService, but some speculate that it will not.

DataStores can easily perform the same task as the PointsService, thus should be used instead to track player data. The DataStoreService in this framework can easily perform the same task.

Once (and if) the new leaderboard system is created, I'll consider writing another service to assist with it.

**Comment by Sleitnick** [comment]
Done. PointsService has been removed and the filelist has been updated.

**Comment by Dog2puppy** [comment]
RIP points. Was kinda an under used feature, but still unfortunate.
