### ISSUE TITLE
RegisterClientEvent/FireAllClientsEvent dosent work?

### ISSUE THREAD

**Issue by BORN2SMUG** [Sleitnick/AeroGameFramework#48]
I recorded video with this issue. Problems is starting on the FireAllClientsEvent stage (client dosent recieve the signal)

https://youtu.be/1tngWclvjH0

**Comment by kevinsarlah** [comment]
You should wait for the player to join the server first.
`repeat wait()until #game.Players:GetPlayers() > 0`

**Comment by Rocky28447** [comment]
@kevinsarlah is correct. You are firing the event before the player joins the server.
