### ISSUE TITLE
rbxPlugin needs to be maintained as open source

### ISSUE THREAD

**Issue by DavidPesta** [Sleitnick/AeroGameFramework#5]
This is a magnificent project and I really want to use it, but I have a concern. Don't be put off by my raw honesty. I love what I see here and I want you to be successful.

Open source software suffers the following weakness: Projects that deserve to be popular cannot become popular because people like me who want to be interested in it cannot be interested in it until it becomes popular first. (It's a catch-22.) Why? Because people like me are afraid that the project that our livelihood depends upon might someday no longer be maintained and fall into disrepair, so we stay away from it. Sadly, that becomes perceived as a lack of interest to the developer, which causes the developer to give up, which reinforces in our minds that our caution was correct and we need to stay away from projects that are not popular. So the vicious cycle of great projects not taking off continues to happen.

But there's some good news. Even if a project stops being maintained and falls into disrepair, there's hope! That's where the strength of open source comes in; an escape hatch. A project that stops being maintained by the original developer can still be maintained by people like me if we're desperate enough to keep our business going. Hurray! :)

But that only works if the entire project is open source. If an important part of the project is not open source or if an important piece of the project stops being openly maintained along with the rest of the project, then I no longer have that assurance. I can no longer make sure that I can use the tool into the far future.

All of that brings me to my specific point.

I noticed that rbxPlugin used to be maintained along with this project. Without rbxPlugin, AeroGameFramework will not work. (Ok, technically it works, but it becomes harder to develop with.) I can see the old code in the project's history, but if improvements to the framework cause the old plugin code to fall out of sync, I have a much bigger problem on my hands if I need to continue maintaining this project if you choose to give up. (Which I hope you never do because you have something very neat here.)

It's great that the plugin was added to the Roblox site, but could you also continue to maintain all updates to the plugin in this repository along with the framework itself? That would be most helpful if I need to maintain this project in the future.

Again, you're doing a great job! Keep up the great work!

**Comment by Sleitnick** [comment]
Hi David,

I appreciate your comments! Please note that the plugin is now being supported on the main Roblox website. This makes it more accessible for users to automatically update when changes are made. I fully intend to continue support of the plugin and the framework since my own games rely on the framework, and thus a small portion of my income also is reliant on this framework.

However, I do agree that it would be nice to keep it in sync here. I will try to do this moving forward.

**Comment by DavidPesta** [comment]
Yes, it is on the main Roblox website, which is very helpful. Your framework is AWESOME and I'm glad that you have many reasons to continue supporting it. Thank you also for hearing me out--keeping the plugin available and in sync here is important to the assured continuity of everyone who invests their efforts into this marvelous framework.

All I can say is, everything you are doing here is extremely brilliant.

**Comment by Sleitnick** [comment]
Reopening issue until I get the plugin back on here

**Comment by Sleitnick** [comment]
Plugin has been re-added to the repository

**Comment by DavidPesta** [comment]
You almost got it. :grin: 

It looks like you added the **_binary_** AeroGameFrameworkPlugin.rbxm.

The old file removed 29 days ago was plugin.rbxmx and the text was fully exposed and could be maintained.

I'd be happy to submit it with a pull request, but I'm not certain if you might have updated it since then.

Thanks again for doing this. :wink:

**Comment by Sleitnick** [comment]
Fixed

**Comment by DavidPesta** [comment]
Perfection! Thank you so much for going the extra mile for me. :grin: :grin: :grin:

**Comment by Sleitnick** [comment]
No problem! I want to make the framework as accessible as possible to everyone, so any suggestions/feedback like this is much appreciated.
