### ISSUE TITLE
Studio freezes forever when starting PlaySolo

### ISSUE THREAD

**Issue by kevinsarlah** [Sleitnick/AeroGameFramework#51]
This bug seems to happen when having AeroGameFramework and Quenty's class converter active at the same time. Disabling either and studio seems to work fine again. 

https://www.youtube.com/watch?v=tvED9SM_8yY
https://www.roblox.com/library/906681627/Quentys-Class-Converter-API-based

**Comment by kevinsarlah** [comment]
After more testing, I found that it happens with other plugins too. This is the one I tested.

https://www.roblox.com/library/948084095/Tag-Editor

**Comment by Sleitnick** [comment]
I have both of those plugins and do not have any issue. This is probably a Roblox issue and not related to this framework.

**Comment by Sleitnick** [comment]
@kevinsarlah is this still an issue for you? I still have not been able to reproduce the issue on my end. I don't want to close this yet in case there's an issue that I can fix.

**Comment by Sleitnick** [comment]
I'm going to close this for now. If the issue arises again, feel free to comment here

**Comment by kevinsarlah** [comment]
yep, studio doesn't crash anymore
