### ISSUE TITLE
[Enchantment] Lazy load addition to better organize modules

### ISSUE THREAD

**Issue by kevinsarlah** [Sleitnick/AeroGameFramework#52]
Here is a small edit that I use.

```lua
-- Setup table to load modules on demand:
function LazyLoadSetup(tbl, folder)
	--Simplify hierarchy of modules
	local modules = {}
	for _, object in ipairs(folder:GetDescendants())do
		if object:IsA("ModuleScript")then
			modules[object.Name] = object
		end
	end
	
	setmetatable(tbl, {
		__index = function(t, i)
			local obj = require(modules[i])
			if (type(obj) == "table") then
				Aero:WrapModule(obj)
			end
			rawset(t, i, obj)
			return obj
		end;
	})
end
````

This allows me to better organize the hierarchy and still use the modules like before. 
![image](https://user-images.githubusercontent.com/20580338/48240577-487a1400-e3a1-11e8-9b5c-721bb0fe89fe.png)
```lua
function UI:Init()
	TimerModule = self.Modules.Timer
	TweenModule = self.Modules.Tween
end
```

**Comment by Sleitnick** [comment]
I actually have plans for a similar feature. It is designed to be somewhat similar, but preserve the dot-notation of the folder. I'm going to close this issue, but your idea is not lost!
