### ISSUE TITLE
Clear Text button on plugin textboxes

### ISSUE THREAD

**Issue by yellowtide** [Sleitnick/AeroGameFramework#6]
Currently it's a little annoying to backspace your way through a textbox's content. An "X" button in the top right corner would be a great addition. Probably should only be visible while hovering.
[`ChangeHistoryService`](http://robloxdev.com/api-reference/class/ChangeHistoryService) too please <3

**Comment by Sleitnick** [comment]
Thanks for the suggestion. This has been added to the backlog.
