### ISSUE TITLE
Plugin acting very strangely

### ISSUE THREAD

**Issue by ThoughtSpinnr** [Sleitnick/AeroGameFramework#67]
https://gyazo.com/829f38db6e1b5ed9f349a28f405f92bc

Inexplicably started showing up along with these errors:
![image](https://user-images.githubusercontent.com/26193486/51569494-821fce80-1e6a-11e9-96ce-ef13abb261f2.png)

**Comment by DannyPlays** [comment]
I believe I saw something about this a week ago, but haven't used it since so I'm not sure if it was this. It most likely was.

**Comment by Sleitnick** [comment]
I've confirmed that this isn't an issue on my end. It seems like the PluginGuis aren't being redrawn properly. I'm trying to see if there's a way I can patch the issue by forcing a redraw, but I'm not sure at the moment.

**Comment by Sleitnick** [comment]
I think this is related to a new static-ui update (see: [https://devforum.roblox.com/t/static-ui-performance-improvements/222557](https://devforum.roblox.com/t/static-ui-performance-improvements/222557))

@Rocky28447

**Comment by Sleitnick** [comment]
@Rocky28447 Same. Let's keep this issue open until the next Roblox release. Just to make sure it actually got fixed.
