### ISSUE TITLE
Documentation Incorrectly Refers To Injected Server Service Property

### ISSUE THREAD

**Issue by Rocky28447** [Sleitnick/AeroGameFramework#7]
"service.Modules" is incorrectly referred to as "service.Objects"

![image](https://user-images.githubusercontent.com/26193486/42302548-99f4b522-7fe9-11e8-9af8-42d5476ab1d2.png)

**Comment by Sleitnick** [comment]
Good catch. During original development, `Modules` was actually named `Objects` instead. Documentation was never corrected to show the change. This inaccuracy has now been resolved.
