### ISSUE TITLE
Consider using timestamped saving for new Data module

### ISSUE THREAD

**Issue by Rocky28447** [Sleitnick/AeroGameFramework#81]
Berezaa proposed an [interesting method of data saving](https://devforum.roblox.com/t/best-way-to-use-datastores-with-minimal-data-loss/32159/3) that would be a great addition to the new Data module as one method of data loss prevention.

**Comment by Sleitnick** [comment]
I've seen this before, and the one problem I have with it is that it treats DataStores as infinite backup storage. Which, technically, we're not given a data limit. However, I think if something like this were implemented, I would want to ensure that it keeps a limited number of data backups.

I'll toss this around more and see if I can design something.
