### ISSUE TITLE
StoreService needs to use new Data module

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/AeroGameFramework#88]
StoreService currently uses the old DataService, but should be updated to use the new Data module.

**Comment by Dog2puppy** [comment]
@Sleitnick Once the new Data module is available on the master branch will the DataService still be updated?

**Comment by Sleitnick** [comment]
Completed in PR https://github.com/Sleitnick/AeroGameFramework/pull/118

**Comment by Sleitnick** [comment]
@Dog2puppy Nope, DataService is removed.
