### ISSUE TITLE
Dark theme option

### ISSUE THREAD

**Issue by kevinsarlah** [Sleitnick/AeroGameFramework#9]
Change plugin colors to fit for studio dark theme 

```lua
print(settings().Studio["UI Theme"] == Enum.UITheme.Dark)
```

**Comment by Sleitnick** [comment]
Hi kevinsarlah! Thanks for the request. So the code you provided will only work for a little while. But Roblox is soon adding a new API to get the theme of Studio, including colors. Once this is released, I will implement it into the plugin to automatically match Studio's theme.

To track this, I'll keep this issue open until the theme feature is implemented.

**Comment by Sleitnick** [comment]
For clarification, some people at Roblox have stated that `settings().Studio["UI Theme"]` will be intentionally removed once the theme API is added.

For testing purposes, I _might_ start working on this earlier using the old piece of code, and will just make sure it's in an isolated container. One thing I want to know is whether or not the new API will provide colors too, or simply an Enum (like it is currently).

**Comment by Sleitnick** [comment]
Two-week update: Still waiting for the new API. I haven't heard any word on it recently.

**Comment by Sleitnick** [comment]
Dark theme has been added. The new API is still not out, but I have designed it so that it should be pretty easy to switch to whatever new API is released.
