### ISSUE TITLE
Deleting folders with the VS Code extension doesn't work

### ISSUE THREAD

**Issue by Xuleos** [Sleitnick/AeroGameFramework#97]
I'm noticing an issue where you can't delete the folders once they've been created in VS code.

![dbe142d95cc5b230a4fee2e35b4ae297](https://user-images.githubusercontent.com/37721396/62741725-fdf9f680-ba09-11e9-8425-920b6ebb71c7.gif)

**Comment by Xuleos** [comment]
AAAAA now I have all these spare folders from me trying to narrow this down to ensure it isn't just happening to nested folders or only under client modules

**Comment by Xuleos** [comment]
Oh yeah, you can't delete modules that have something nested in them

**Comment by Sleitnick** [comment]
BTW I've replicated this into the actual repo for the extension (a different repo than this):

https://github.com/Sleitnick/AeroGameFramework-VSCE/issues

**Comment by Sleitnick** [comment]
This has been fixed https://github.com/Sleitnick/AeroGameFramework-VSCE/commit/41bbd08be0dbc8941d9336a1aa12ca50f0fc0358
